/**
 * Bread Rise — case studies.
 * Files live in /public/media/<slug>/. Each base name resolves into a
 * responsive trio of WebP variants generated by scripts/optimize-images.sh:
 *   <base>-200.webp / <base>-800.webp / <base>-1280.webp
 * The asset() helper prepends the GitHub Pages basePath at runtime.
 */

import { asset } from "@/lib/utils";

const ASPECT_W = 1280;
const ASPECT_H = 1715; // 1280×1715 ≈ 3:4 portrait used by every photo.

export type ImgSrc = {
  /** Default `src` — the 800w variant works as the fallback. */
  src: string;
  /** Tiny thumb (~200w) for clusters and offscreen plates. */
  thumb: string;
  /** Full responsive `srcset` covering 200 / 800 / 1280 widths. */
  srcSet: string;
  /** Intrinsic aspect ratio in pixels — set as width/height on `<img>`. */
  width: number;
  height: number;
};

function img(slug: string, base: string): ImgSrc {
  const v = (size: 200 | 800 | 1280) =>
    asset(`/media/${slug}/${base}-${size}.webp`);
  return {
    src: v(800),
    thumb: v(200),
    srcSet: `${v(200)} 200w, ${v(800)} 800w, ${v(1280)} 1280w`,
    width: ASPECT_W,
    height: ASPECT_H,
  };
}

export type Project = {
  id: string;
  index: string;
  title: string;
  client?: string;
  year: number;
  discipline: string[];
  /** Service tags shown on the project detail page. */
  services?: string[];
  /** Long-form description. Use \n\n between paragraphs. */
  description?: string;
  /** Optional bullet list rendered under "Visual signatures". */
  visualSignatures?: string[];
  /** Optional bullet list rendered under "Designed for". */
  designedFor?: string[];
  /** First image is also used as the cover/headline plate. */
  gallery: ImgSrc[];
};

export const projects: Project[] = [
  {
    id: "women-are-beautiful",
    index: "01",
    title: "Women Are Beautiful",
    client: "—",
    year: 2026,
    discipline: ["AI Production", "Editorial"],
    services: [
      "AI Editorial Production",
      "Creative Direction",
      "Visual Identity Systems",
      "Casting & Character Design",
      "Art Direction",
      "Digital Fashion Imagery",
    ],
    description:
      "“Women Are Beautiful” is an AI editorial study of femininity, age, and presence. The project rejects conventional beauty narratives in favor of raw elegance, emotional texture, and hyperreal visual storytelling.\n\nBuilt through AI production and editorial direction, the series transforms mature beauty into a striking visual statement, where skin, movement, vulnerability, and strength become the narrative itself. The result exists somewhere between luxury campaign imagery and synthetic documentation.",
    gallery: [
      img("women-are-beautiful", "IMG_3393"),
      img("women-are-beautiful", "IMG_3392"),
      img("women-are-beautiful", "IMG_3390"),
      img("women-are-beautiful", "IMG_3388"),
      img("women-are-beautiful", "IMG_3387"),
      img("women-are-beautiful", "IMG_3385"),
      img("women-are-beautiful", "IMG_3384"),
      img("women-are-beautiful", "IMG_3383"),
      img("women-are-beautiful", "IMG_3382"),
    ],
  },
  {
    id: "runway-training",
    index: "02",
    title: "Runway Training",
    client: "—",
    year: 2026,
    discipline: ["AI Production", "Direction", "Fashion"],
    services: [
      "AI Fashion Production",
      "Wearable Concept Design",
      "Creative Direction",
      "Movement Research",
      "Performance Styling",
      "Visual Campaign Development",
      "Fashion Narrative Systems",
    ],
    description:
      "“Runway Training” reimagines fashion through physical discipline and constructed beauty. Combining AI-generated fashion imagery with athletic environments, the project reframes the language of luxury fashion into a sweat-soaked, focused, and constantly observed.\n\nThe series merges gym culture with runway aesthetics, where strength becomes choreography and exhaustion turns into styling. Through exaggerated poses, athletic gear, hyperreal body language, the work examines how contemporary femininity is shaped through performance, pressure, and visibility.",
    gallery: [
      img("runway-training", "IMG_4065"),
      img("runway-training", "IMG_4072"),
      img("runway-training", "IMG_4073"),
      img("runway-training", "IMG_4082"),
      img("runway-training", "IMG_4122"),
      img("runway-training", "IMG_4131"),
      img("runway-training", "IMG_4132"),
      img("runway-training", "IMG_4134"),
      img("runway-training", "IMG_4138"),
      img("runway-training", "IMG_4160"),
      img("runway-training", "IMG_4161"),
      img("runway-training", "IMG_4162"),
      img("runway-training", "IMG_4163"),
    ],
  },
  {
    id: "wet",
    index: "03",
    title: "Wet",
    client: "—",
    year: 2026,
    discipline: ["AI Production", "Visual Identity"],
    services: [
      "AI Visual Production",
      "Beauty Art Direction",
      "Concept Development",
      "Editorial Image Systems",
      "Texture & Surface Research",
      "Digital Beauty Campaigns",
    ],
    description:
      "“Wet” explores the visual tension between intimacy, gloss, and artificial perfection. Through hyper-detailed AI imagery, the project transforms moisture, skin, reflection, and bodily texture into a controlled visual language suspended between beauty campaign and sensory study.\n\nRather than documenting the body naturally, the series exaggerates surface, shine, and physical detail until the images begin to feel almost synthetic: seductive, clinical, and emotionally distant at the same time. Every frame focuses on texture as identity: wet skin, breath, gloss, saliva, light.",
    gallery: [
      img("wet", "IMG_3948"),
      img("wet", "IMG_3958"),
      img("wet", "IMG_3960"),
      img("wet", "IMG_3962"),
      img("wet", "IMG_3964"),
      img("wet", "IMG_3965"),
      img("wet", "IMG_3966"),
    ],
  },
  {
    id: "man-accessories",
    index: "04",
    title: "Man Accessories",
    client: "—",
    year: 2026,
    discipline: ["AI Production", "Editorial", "Direction"],
    services: [
      "AI Visual Production",
      "Beauty Art Direction",
      "Concept Development",
      "Editorial Image Systems",
      "Texture & Surface Research",
      "Digital Beauty Campaigns",
    ],
    description:
      "“Man Accessories” explores masculinity through restriction, ornament, and engineered identity. Using AI-generated editorial imagery, the project transforms metallic and architectural elements into the construction of the body, suspended between fashion accessory, protective armor, and invasive object.\n\nRather than functioning as wearable products, the pieces operate as visual statements: aggressive yet elegant, mechanical yet intimate. The series examines how masculinity can be constructed, exaggerated, and aestheticized through artificial design language and hyper-controlled imagery.",
    gallery: [
      img("man-accessories", "IMG_2966"),
      img("man-accessories", "IMG_2980"),
      img("man-accessories", "IMG_2985"),
      img("man-accessories", "IMG_2988"),
      img("man-accessories", "IMG_2996"),
      img("man-accessories", "IMG_2997"),
    ],
  },
  {
    id: "my-body-made-of-petals",
    index: "05",
    title: "My Body Made of Petals",
    client: "—",
    year: 2026,
    discipline: ["AI Production", "Editorial", "Fine Art"],
    services: [
      "Creative Direction",
      "AI Fashion Image Creation",
      "AI Fashion Video / Motion",
      "Visual Identity for Fashion & Beauty Brands",
      "Art Direction for Social Media",
    ],
    description:
      "My Body Made of Petals is a sensual high-fashion visual series exploring the transformation of the human body into living floral sculpture. Inspired by Vogue beauty editorials, luxury perfume campaigns, and contemporary body art photography, the project merges glossy skin, sculptural posing, and well flower petals into cinematic compositions.\n\nThe body becomes a canvas covered in luminous petals with an almost liquid texture: soft, reflective, organic, and surreal. Every frame is built around macro body details, dramatic studio lighting, rich black backgrounds, and couture-inspired floral styling.\n\nThe project exists between fashion photography, beauty campaigns, and fine art.",
    visualSignatures: [
      "Glossy oil-like petals",
      "Macro body compositions",
      "Black seamless background",
      "Cinematic studio light",
      "Artificial light on skin",
      "Sculptural feminine poses",
      "Luxury Vogue-inspired aesthetic",
      "Sensual but minimal visual language",
      "Floral body couture",
    ],
    designedFor: [
      "Fashion editorials",
      "Perfume & skincare brands",
      "Album covers",
      "Luxury visual identities",
      "Creative concept reels",
      "AI fashion campaigns",
    ],
    gallery: [],
  },
];

export type Plate = {
  key: string;
  image: ImgSrc;
  projectId: string;
  projectTitle: string;
  projectIndex: string;
  /** Filename label rendered under the References cluster thumbnails. */
  fileLabel: string;
};

function fileLabelFor(image: ImgSrc): string {
  // strip the responsive `-800` suffix and the extension so the label
  // matches the source filename ("IMG_3393").
  const last = image.src.split("/").pop() ?? image.src;
  return last.replace(/-(?:200|800|1280)\.webp$/i, "");
}

/**
 * Flat list of every project image, tagged with its parent project.
 * Used by the 3D stack and the References wall.
 */
export const plates: Plate[] = projects.flatMap((p) =>
  p.gallery.map((image, i) => ({
    key: `${p.id}-${i}`,
    image,
    projectId: p.id,
    projectTitle: p.title,
    projectIndex: p.index,
    fileLabel: fileLabelFor(image),
  })),
);

/**
 * 12 plates for the hero stack — distributed across all projects so
 * every project shows up at least once.
 */
export const stackPlates: Plate[] = (() => {
  const out: Plate[] = [];
  let i = 0;
  while (out.length < 12 && i < 50) {
    for (const p of projects) {
      const image = p.gallery[i];
      if (!image) continue;
      out.push({
        key: `${p.id}-stack-${i}`,
        image,
        projectId: p.id,
        projectTitle: p.title,
        projectIndex: p.index,
        fileLabel: fileLabelFor(image),
      });
      if (out.length >= 12) break;
    }
    i += 1;
  }
  return out;
})();

/** Project plates used by the References cluster. */
export const allReferencePlates: Plate[] = plates;
